--- 
name: Run Deno tests
on:
  workflow_run:
    workflows: ["Deno lint"]
    types: ["completed"]
    branches:
      - "main"
      - "dev"

permissions:
  contents: read

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run tests
        run: deno test --allow-env --allow-read --allow-write --allow-net --unstable
