--- 
name: Deno lint
on:
  push:
  pull_request:
    branches:
      - "main"
      - "dev"

permissions:
  contents: read

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run linter
        run: deno lint
