--- 
name: Deno linting and unit tests
on:
  workflow_call:
  push:
    branches-ignore:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run linter
        run: deno lint

  test:
    # If (push to master or dev branch) OR (pull_request)
    if: ${{ (github.event_name == 'push' && ( github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' ) ) || github.event_name == 'pull_request' }}
    needs: lint
    runs-on: self-hosted
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run tests
        run: deno test --allow-env --allow-read --allow-write --allow-net --unstable
