---
name: Deploy to prod
on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  deployment:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: SSH Key Creation
        run: |
          echo "${{ secrets.DISCORD_USER_SSH_KEY}}" > .key
          chmod 0600 .key
          ssh-keyscan -H ${{ secrets.DISCORD_HOST }} >> ./.hosts
          chmod 0600 ./.hosts
      - name: Stop StarBot
        run: ssh -o UserKnownHostsFile=./.hosts -i .key ${{ secrets.DISCORD_USER }}@${{ secrets.DISCORD_HOST }} "systemctl --user stop StarBot; rm -rf ~/bot/*"
      - name: Upload Code for Deployment
        run: scp -o UserKnownHostsFile=./.hosts -i .key -r * ${{ secrets.DISCORD_USER }}@${{ secrets.DISCORD_HOST }}:~/bot/
      - name: Start StarBot
        run: ssh -o UserKnownHostsFile=./.hosts -i .key ${{ secrets.DISCORD_USER }}@${{ secrets.DISCORD_HOST }} "systemctl --user start StarBot"
