---
name: Deployment
on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      inst-path:
        required: true
        type: string
    secrets:
      ssh-key:
        required: true
      hostname:
        required: true
      username:
        required: true
  
permissions:
  contents: read

jobs:  
  deployment:
    runs-on: self-hosted
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Cache Container
        id: image-cache
        uses: actions/cache@v3
        with:
          path: image
          key: starbot_container-${{ hashFiles('flake.*','**.c','**.h') }}
      - name: SSH Key Creation
        run: |
          echo "${{ secrets.ssh-key}}" > .key
          chmod 0600 .key
          ssh-keyscan -H ${{ secrets.hostname }} >> ./.hosts
          chmod 0600 ./.hosts
      - name: Stop Bot service
        run: ssh -o UserKnownHostsFile=./.hosts -i .key ${{ secrets.username }}@${{ secrets.hostname }} "systemctl --user stop ${{ inputs.service-name }}"
      - name: Upload Code and Image for Deployment
        run: rsync -ar --delete -e "ssh -o UserKnownHostsFile=./.hosts -i .key" * ${{ secrets.username }}@${{ secrets.hostname }}:${{ inputs.inst-path }}/
      - name: Start Bot service
        run: ssh -o UserKnownHostsFile=./.hosts -i .key ${{ secrets.username }}@${{ secrets.hostname }} "systemctl --user start ${{ inputs.service-name }}"
