---
name: Deploy to prod
on:
  workflow_run:
    workflows: ["Run Deno tests"]
    types: ["completed"]
    branches: ["main"]
  
permissions:
  contents: read

jobs:  
  deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: SSH Key Creation
        run: |
          echo "${{ secrets.DISCORD_USER_SSH_KEY}}" > .key
          chmod 0600 .key
          ssh-keyscan -H ${{ secrets.DISCORD_HOST }} >> ./.hosts
          chmod 0600 ./.hosts
      - name: Stop StarBot
        run: ssh -o UserKnownHostsFile=./.hosts -i .key ${{ secrets.DISCORD_USER }}@${{ secrets.DISCORD_HOST }} "systemctl --user stop StarBot; rm -rf ~/bot/*"
      - name: Upload Code for Deployment
        run: scp -o UserKnownHostsFile=./.hosts -i .key -r * ${{ secrets.DISCORD_USER }}@${{ secrets.DISCORD_HOST }}:~/bot/
      - name: Start StarBot
        run: ssh -o UserKnownHostsFile=./.hosts -i .key ${{ secrets.DISCORD_USER }}@${{ secrets.DISCORD_HOST }} "systemctl --user start StarBot"
