---
name: Deploy to server based on branch
on:
  push:
    branches:
      - main
      - dev

jobs:
  pre-deploy-test:
    uses: ./.githubworkflows/deno-tests.yml
  
  deploy-dev:
    if: ${{ github.ref == 'refs/heads/dev' }}
    needs: pre-deploy-test
    uses: ./.github/workflows/deploy.yml
    with:
      service-name: "StarBot-Test"
      inst-path: "bot-test"
    secrets:
      username: ${{ secrets.DISCORD_USER }}
      hostname: ${{ secrets.DISCORD_HOST }}
      ssh-key: ${{ secrets.DISCORD_USER_SSH_KEY }}

  deploy-prod:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: pre-deploy-test
    uses: ./.github/workflows/deploy.yml
    with:
      service-name: "StarBot"
      inst-path: "bot"
    secrets:
      username: ${{ secrets.DISCORD_USER }}
      hostname: ${{ secrets.DISCORD_HOST }}
      ssh-key: ${{ secrets.DISCORD_USER_SSH_KEY }}
